cerfacs-globc/icclim

- icclim/set_globattr.py
Added a new type of seasonal group object in OCGIS that has the property "icclim_mode". The returned string representation of the season may be easily inserted into a history string.
> history attribute for seasons

- setup.py
Fixing import issue for util from the setup config in setup.py
> Fixing import issue from setup.py

- icclim/calc_percentiles.py
Update to fix the bug if the condition for the leap year
> Fix bug with leap year for bootstrapping method

- MANIFEST.in
- icclim/config_indice.json
- icclim/icclim.py
- icclim/util/check.py
- icclim/util/logging_info.py
- icclim/util/user_indice.py
- icclim/util/util_nc.py
- setup.py
Structure the metadata part on icclim.py 
Creation of check.py which include some check related to the data type. 
The indice_type has been added on config_indice.json, the next step consist to use the json file instead of the maps.py file.
> Structure the metadata part on icclim.py

- icclim/calc_percentiles.py
- icclim/config_indice.json
- icclim/icclim.py
- icclim/util/user_indice.py
The structure change on config_indice.json implied to change user_indice.py while importing the data from the dictionnary.
> Solving critical issue on user_indice.py

- icclim/config_indice.json
- icclim/icclim.py
- icclim/util/logging_info.py
- icclim/util/user_indice.py
Comment the raising error for var_name and solve logging issue.
It should allow to check if the issue #54 is solved
> Comment the raising error for var_name and solve logging issue

- icclim/calc_percentiles.py
Removing bugging line in calc_percentile for anaconda
> Removing bugging line in calc_percentile for anaconda

- icclim/util/read.py
Solving issue #58 
It was due to a wrong argument name in read.py
> Fix bug in read.py

- HISTORY.rst
- icclim/models/ecad_indices.py
icclimversion: 5.0.0rc1 
Fix default variable of hd17 index.
> FIX: HD17 was expecting the wrong variable

- icclim/ecad_functions.py
- icclim/main.py
- icclim/models/ecad_indices.py
- icclim/models/index_config.py
It's necessary to chunk on time dimension for consecutive day indices.
Only bootstrapped indices can benefit from time:-1 chunking
> FIX: Performance issue

- .github/ISSUE_TEMPLATE.md
- doc/source/references/ecad_functions_api.rst
- doc/source/references/icclim_index_api.rst
- icclim/ecad_functions.py
- icclim/main.py
- icclim/models/index_config.py
> DOC/FIX: fix some display issues

- doc/source/explanation/climate_indices.rst
- doc/source/explanation/index.rst
- doc/source/explanation/xclim_and_icclim.rst
- doc/source/references/release_notes.rst
This article is a start to clarify the scope of icclim vis-à-vis xclim.
- [NA] These changes were tested with real data and unit tests cover them as well.
Wrote an article to explain why icclim exists and may be relevant in 2022.
> DOC: Add disambiguation article

- .github/workflows/ci.yml
- doc/source/references/release_notes.rst
- environment.yml
- setup.py
We follow np, xr, xclim on this.
> MAINT: Drop python 3.7

- environment.yml
- requirements.txt
- setup.py
We need latest xclim version for 5.0 release.
This commit also align other dependencies versions.
> MAINT: Update dependencies versions

- .github/workflows/ci.yml
- doc/source/dev/ci.rst
- doc/source/references/release_notes.rst
- [N/A] These changes were tested with real data and unit tests cover them as well.
Add code coverage to CI:
- Added pytest-cov run in icclim workflow
- Added [github action] (https://github.com/MishaKav/pytest-coverage-comment) to comment on PR.
> ENH: Add coverage to CI

- doc/source/references/icclim_index_api.rst
- doc/source/references/release_notes.rst
- icclim/ecad_functions.py
- icclim/models/ecad_indices.py
- icclim/tests/test_ecad_indices.py
- icclim/user_indices/operators.py
- tools/extract-icclim-funs.py
Made CSDI and WSDI threshold configurable.
Note:
- For now the metadata is updated within icclim but it would be better to do it in xclim.
> ENH: Add threshold config to CSDI and WSDI

- README.rst
- [n/a] A short description of the changes has been added to `doc/source/references/release_notes.rst`.
Fix readme example which was showing deprecated "indice" wording.
> FIX: Readme example

- doc/source/how_to/dask.rst
- doc/source/references/icclim_index_api.rst
- doc/source/references/release_notes.rst
> DOC: Clarify some doc

- doc/source/references/release_notes.rst
- environment.yml
- icclim/__init__.py
- icclim/pre_processing/rechunk.py
- requirements.txt
- requirements_dev.txt
- setup.py
- Bump version to 5.2
- Fix a minor issue on `create_optimized_zarr_store`
- Upgrade to rechunker 0.5.
> Maint: Prepare 5.2 release

- README.rst
> DOC: Cleanup Readme file

- README.rst
- doc/source/dev/release_process.rst
- environment.yml
- icclim/models/frequency.py
- icclim/tests/test_main.py
- requirements.txt
- requirements_dev.txt
> Maint: Make slice_mode typing accept Frequency

- doc/source/dev/release_process.rst
- doc/source/references/release_notes.rst
- icclim/__init__.py
- icclim/main.py
- icclim/models/constants.py
- icclim/tests/test_main.py
- setup.py
icclim now adds `- icclim version: {icclim.__version__}` to history.
> ENH: Add icclim version to history

- README.rst
> MAINT: Add badge to Zenodo DOI

- doc/source/references/release_notes.rst
- icclim/models/frequency.py
- icclim/tests/test_frequency.py
Fix issue with custom seasons ending in december.
The time_bounds creation was trying to instantiate a 13th month which does not make any sense.
> FIX: season ending in december

- doc/source/references/release_notes.rst
- icclim/models/constants.py
- icclim/tests/test_input_parsing.py
- For compatibility reason we still accept "adjust" (lowercase) suffix.
Add "Adjust" suffix to auto detection of variable.
> FIX: Add {xxx}Adjust as valid variable aliases

- doc/source/references/release_notes.rst
- icclim/models/constants.py
- requirements.txt
- setup.py
> Bump to 5.4.0

- .pre-commit-config.yaml
- README.rst
- doc/source/how_to/dask.rst
- doc/source/how_to/ocgis.rst
- doc/source/how_to/recipes_custom.rst
- doc/source/how_to/recipes_ecad.rst
- doc/source/references/custom_indices.rst
- doc/source/references/ecad_functions_api.rst
- doc/source/references/icclim_index_api.rst
- doc/source/references/release_notes.rst
- icclim/pre_processing/in_file_dictionary.py
- icclim/pre_processing/rechunk.py
- tools/extract-icclim-funs.py
Add BlackDoc to our CI in order to keep the doc example as clean as our code base.
> MAINT: Add BlackDoc gh action

- README.rst
> FIX: link to logo

- icclim/models/threshold.py
Added bare operand in metadata generation.
Fix threshold_min_value metadata
> FIX: `threshold_min_value` metadata generation

- requirements_dev.txt
Upgrade np to >= 1.22 in our dev dependencies.
icclim users will not be affected by this change, this PR is mainly to answer dependabot complaints.
> FIX: "security" issue

- icclim/models/__init__.py
- icclim/models/threshold.py
> DOC: Add some doc on thresholds

- doc/source/references/release_notes.rst
- environment.yml
- requirements.txt
- requirements_dev.txt
- setup.py
- n/a Unit tests cover the changes.
- n/a The relevant documentation has been added or updated.
- Upgrade to use latest xclim version (0.39)
- AIso prepare for icclim 6.1 release
> MAINT: Upgrade to xclim 0.39

- icclim/ecad/ecad_indices.py
- icclim/generic_indices/generic_indicators.py
There's one line in the code where `indicator=GenericIndicatorRegistry.Minimum` needs to be changed to `indicator=GenericIndicatorRegistry.Maximum`.
> FIX: Bug fix for TNx

- doc/source/_static/logo_icclim_colored__displayed.svg
- doc/source/_static/logo_icclim_grey__displayed.svg
- doc/source/_static/logo_icclim_white__displayed.svg
- doc/source/references/release_notes.rst
- icclim/_generated_api.py
- icclim/models/constants.py
- setup.py
> [MAINT] Bump to 6.1.3

- doc/source/references/release_notes.rst
- environment.yml
- requirements.txt
- requirements_dev.txt
- setup.py
Maintenance PR to make icclim 6.3.0 use the latest xclim version (0.42)
> MAINT: Upgrade to xclim 0.42

- doc/source/references/release_notes.rst
> BUMP: 6.3.0

- .github/workflows/ci.yml
- .readthedocs.yml
- doc/source/references/release_notes.rst
- doc/source/tutorials/installation.rst
- environment.yml
- setup.py
> MAINT: Make python 3.9 the minimal compatible version
