cerfacs-globc/icclim

icclim/set_globattr.py

If there is not a default string representation for an OCGIS calculation grouping, convert it to a string by default.

add support for other calculation grouping in history attribute

---

icclim/__init__.py

I noticed the version was not updated in ``icclim/__init__.py``. This PR updates the version number.

Incremented version in __init__ to 4.1.1

---

icclim/calc_indice.py
icclim/calc_percentiles.py
icclim/util/calc.py

I am building `icclim` packages for Python 3.5/3.6 and encountered some minor import issues. This PR contains a couple quick fixes. The issue is related to changes in relative imports with Python 3.*. I have a test for this import combination that was failing during the build.

Fixed imports for Python 3.5/3.6

---

icclim/calc_indice.py

This request aims to solve the issue #23 
It make sense to switch from Kelvin to Celsius for the TN and TX since the results are temperature in Kelvin. However, the HD17 represents the sum of the difference of two temperature. It doesn't change anything either we are in Kelvin or Celsius since we sum the difference.

Change TN & TX from Kelvin to Celsius

---

icclim/calc_percentiles.py

The function name in calc_percentiles.py was still included the "with_bootstrapping" because there was 2 different functions to compute with_bootstrapping and without_bootstrapping. Since the 2 methods have been merged in one function the function name is confusing.

Change the function name for percentile

---

icclim/config_indice.json
icclim/icclim.py
icclim/util/read.py

Add slice_mode in the config file, create a read.py script to read the config file from outside of the icclim module.
Currently the read.py has no utility within the icclim module but will be the main program to read netcdf and config file. It is already used in the WPS currently in development for the DARE project.

Add slice_mode in the config file and create a read.py script

---

icclim/config_indice.json
icclim/util/read.py

Add utility function to access data structure from config_indice.json to syncrhonize the wps on C4I and icclim configuration.
The new function on read.py allow to access directly the indice or slice_mode available on icclim. If an indice is added to icclim, he should be directly added on the wps - if C4I has the new version of icclim.

Add utility function to access data structure from config_indice.json

---

icclim/config_indice.json

I found another typo in the config_indice.json. CSDI was mispelled CDSI.

Fix typo in config_indice.json

---

doc/source/conf.py
doc/source/explanation/index.rst
setup.cfg

The pre-commit linting was breaking the sphynx build.
The cause is the `import icclim` which must be done after updating the sys.path.

Fix: improper lint on doc conf

---

requirements_dev.txt

Add main requirements to dev requirements file.
This should fix the readthedoc build.

Fix: missing dev requirements

---

doc/source/references/release_notes.rst
doc/source/tutorials/installation.rst
icclim/__init__.py

At last the official release of icclim v5 (5.0.0).
See `release-notes.rst` for all changes brought by this version.
Some issues raised in #101 will be part of future releases:
- Contribution guide
- Comparison with climdex/climpact (in progress)
- Example update in our doc.
- Add a gallery
- Windows OS test campaign an bug fixes
- Unit tests...
- icclim logo (in progress within is-enes3)

MAINT: Bump to 5.0.0

---

doc/source/references/release_notes.rst
icclim/__init__.py

Bump to 5.0.1 for license fixes.
This should solve conda release issues.

Bump to 5.0.1

---

doc/source/references/release_notes.rst
icclim/pre_processing/rechunk.py
setup.py

- Fixed installation from sources
When doing `import icclim.__version__` in setup.py, we were trying to import the whole API declared in __init__.py.
This would fail because when doing `pip install setup.py`, the installation of dependency packages is done long after the initial import. Thus we remove the import and duplicated the version number.
The side effect is the duplication of icclim version number instead of relying on a single constant.
This will have a low maintenance cost.
- Also made a small disk usage optimization for rechunker.
We try to remove the temporary zarr stores as soon as they are unnecessary.

FIX: installation from sources

---

.github/workflows/ci.yml
doc/source/references/release_notes.rst
setup.py

- Pinned dask to <2022.01.1
- Lower and remove some unnecessarily high pinned numbers
Update version pinning
For rechunker to work we must pin dask to <2022.01.1. 
We were also pinning to high version numbers some dependency for no reason.

MAINT: pin and unpin versions

---

.github/workflows/ci.yml
doc/source/references/release_notes.rst

Within the CI, make `test` job fail when tests are failing.
This was cause by the pipe to `tee` which was overriding the exit code of pytest.

Fix CI not properly failling on errors

---

README.rst
doc/source/how_to/dask.rst
doc/source/references/release_notes.rst
icclim/ecad_functions.py
icclim/icclim_logger.py
icclim/main.py
icclim/pre_processing/rechunk.py
icclim/tests/test_rechunk.py
icclim/utils.py

Following the discussion on S.O[0] it seems not so optimal to always use a chunking schema where a dimension is unchunked.
Now instead of passing a `dim` which will be unchunked, `create_optimized_zarr_store` accepts a `chunking` dictionary.
The default behavior is unchanged though, it will still create a zarr store unchunked on time.
This seems handy because the climate indices relying on daily percentiles will still be much faster if there is no chunk on "time" because of the `map_block` used in xclim bootstrapping.py.
[0] https://stackoverflow.com/questions/71570003/why-does-the-amount-of-dask-task-increase-with-an-optimized-chunking-compared

MAINT: Rework rechunking

---

doc/source/references/release_notes.rst
environment.yml
icclim/ecad/ecad_functions.py
setup.py

Numpy is no longer pin to below 1.22.
This propagates the changes made for icclim v5.2.2

MAINT: Remove constraint on numpy version

---

doc/source/references/release_notes.rst
icclim/ecad/ecad_functions.py
icclim/pre_processing/input_parsing.py

- When giving input as a list of netcdf files, the coordinate values are now merged using the `override` strategy, thus the first file with a given dimension define this dimension for all the files.
- Fix the output unit of some indices (from "ºC" to "degree_Celsius")

Fix e-obs dataset file merge

---

doc/source/references/release_notes.rst
icclim/main.py
icclim/pre_processing/input_parsing.py
icclim/tests/test_main.py

When chunking on the Dataset we would try to chunk variables that
have nothing to do with the computation such as `time_bds`.
This is unnecessary plus, if the variable is not properly decoded
and keep a dtype "object", dask would fail to chunk it.
Instead, we now chunk DataArray(s) that we are sure to read for the computation.
Ignore time_bounds and other variables that are not used for the computation when chunking the data.

FIX[#199]: Make the chunking on DataArrays

---

.gitattributes
.github/CONTRIBUTING.rst
.github/workflows/ci.yml
README.rst
doc/source/_static/css/custom.css
doc/source/_static/logo_icclim_colored__base.svg
doc/source/_static/logo_icclim_colored__displayed.svg
doc/source/_static/logo_icclim_favicon__base.svg
doc/source/_static/logo_icclim_favicon__displayed.ico
doc/source/_static/logo_icclim_grey__base.svg
doc/source/_static/logo_icclim_grey__displayed.svg
doc/source/_static/logo_icclim_white__base.svg
doc/source/_static/logo_icclim_white__displayed.svg
doc/source/conf.py
doc/source/references/icclim_index_api.rst
doc/source/references/release_notes.rst
requirements.txt
requirements_dev.txt
tools/update_logo_version.py

- [na] Unit tests cover the changes.
- [na] These changes were tested on real data.
Add icclim logo
This PR introduce [git lfs ](https://git-lfs.github.com/) to icclim repository to store logo images.
This doesn't break anything per se, but contributors would need to manually init lfs locally if (and only if) they need to edit lfs stored files.
As for the why, even if our logo svg images are quite small (around 65KB), every version of icclim will update the version number within the svg. There is absolutely no need to version each updated logo image that's why git lfs seems to be a good option here. It allows to 1. store the latest image version in the repo, 2. store the updates within a lightweight text file.
In the future, we could also benefit from lfs when we would add a netcdf …

Enh: release the krak... bird!

---

README.rst
doc/source/references/ecad_functions_api.rst
doc/source/references/release_notes.rst
icclim/_generated_api.py
icclim/ecad/ecad_indices.py
icclim/generic_indices/generic_indicators.py
icclim/generic_indices/generic_templates.py
icclim/generic_indices/threshold_templates.py
icclim/main.py
icclim/models/constants.py
icclim/models/frequency.py
icclim/models/logical_link.py
icclim/models/registry.py
icclim/models/threshold.py
icclim/pre_processing/input_parsing.py
icclim/tests/test_main.py
icclim/tests/test_threshold.py
icclim/utils.py
setup.cfg

Add new Threshold sub-type BoundedThreshold.
It wraps 2 threshold bounded by a LogicalLink ("and" or "or") into one Htreshold that can be computed on a single climate variable.
This is particularly useful for some ECAD's indices such as `DDnorth` where we must count the exceedance of a single climate variable (dd) over a threshold AND below another one.
In DDNorth case it would be `-45º< dd <45º`

ENH: Add BoundedThreshold

---

doc/source/how_to/index.rst
doc/source/how_to/recipes_custom.rst
doc/source/how_to/recipes_generic.rst
doc/source/references/ecad_functions_api.rst
doc/source/references/generic_functions_api.rst
doc/source/references/icclim_index_api.rst
doc/source/references/release_notes.rst
icclim/_generated_api.py
icclim/ecad/ecad_indices.py
icclim/ecad/xclim_binding.py
icclim/generic_indices/generic_indicators.py
icclim/generic_indices/standard_variable.py
icclim/models/climate_variable.py
icclim/models/constants.py
icclim/tests/test_generated_api.py
icclim/tests/test_main.py
icclim/utils.py
requirements.txt
requirements_dev.txt
tools/extract-icclim-funs.py

Draft how we should bind existing xclim indices into icclim v6 to complete the ECAD list.
- Add some ECAD indices that can be easily bind to xclim's indicators.
This includes `{GSL, SPI3, SPI6}`.
The same approach could be used for other missing indices that **can't** be generified and that are available within xclim.
- Add some documentation for generic indices.
This PR is also related to #204 but does not fully resolve it.

[ENH] Bind xclim indicators to missing ECAD indices

---

.pre-commit-config.yaml
doc/source/references/release_notes.rst
environment.yml
requirements.txt
requirements_dev.txt
setup.py

Pin xclim to 0.39
Fixes:
- installation of icclim on pipy (no issue opened yet)
- https://github.com/Ouranosinc/xclim/issues/1294
This Pr should **not** be merged into the main trunk (master).
The fixing commit will be tagged 6.1.6 and be published to pipy and conda-forge

FIX: Pin xclim to 0.39

---

doc/source/references/release_notes.rst
environment.yml
requirements.txt
requirements_dev.txt
setup.py

Also pin xclim to any 0.43.x instead of `0.43.0`
Upgrade to latest xclim version

MAINT: Upgrade to xclim 0.43

---

doc/source/_static/logo_icclim_colored__displayed.svg
doc/source/_static/logo_icclim_grey__displayed.svg
doc/source/_static/logo_icclim_white__displayed.svg
doc/source/references/release_notes.rst
icclim/models/constants.py
setup.py

Bump icclim to 6.5.0.
This release fixes #256  and #281.
It requires xclim version to be between 0.45 and 0.47 due to breaking changes in `to_agg_unit` utility function in xclim 0.45.

BUMP: 6.5.0

---

pyproject.toml

Some lint rules of rust are unnecessary for unit and integrations tests.
This PR allows the following rules
-  "S101", # Allow asserts allowed in tests.
- "ARG", # Allow unused function args for tests fixtures.
-  "FBT" # Allow booleans as positional arguments in tests.

MAINT: Ignore some rules for tests
